In [2]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     --------------------------------------- 0.0/11.9 MB 320.0 kB/s eta 0:00:37
     --------------------------------------- 0.1/11.9 MB 656.4 kB/s eta 0:00:18
      --------------------------------------- 0.2/11.9 MB 1.6 MB/s eta 0:00:08
     - -------------------------------------- 0.5/11.9 MB 2.7 MB/s eta 0:00:05
     --- ------------------------------------ 0.9/11.9 MB 4.1 MB/s eta 0:00:03
     --- ------------------------------------ 1.1/11.9 MB 4.0 MB/s eta 0:00:03
     ---- ----------------------------------- 1.3/11.9 MB 4.1 MB/s eta 0:00:03
     ---- ----------------------------------- 1.4/11.9 MB 4.1 MB/s eta 0:00:03
     ---- ----------------------------------- 1.4/11.9 MB 4.1 MB/s eta 0:00:03
     ---- ----------------------------------- 1.4/11.9 MB 4.1 MB/s eta 0:00:03
     ----- ---------------------------------- 1.5/11.9 MB 2.9 MB/s eta 0:00:04
     ----- ---------------------------------- 1.5/11.9 MB 2.9 MB/s eta 0:00:04
     ----- ---------------------------------- 1.5/11.9 MB 2.9 MB/s eta 0:00:04
     -------- ------------------------------- 2.5/11.9 MB 3.9 MB/s eta 0:00:03
     --------- ------------------------------ 2.8/11.9 MB 3.9 MB/s eta 0:00:03
     ---------- ----------------------------- 3.0/11.9 MB 3.9 MB/s eta 0:00:03
     ---------- ----------------------------- 3.2/11.9 MB 3.9 MB/s eta 0:00:03
     ----------- ---------------------------- 3.3/11.9 MB 3.9 MB/s eta 0:00:03
     ----------- ---------------------------- 3.3/11.9 MB 3.9 MB/s eta 0:00:03
     ----------- ---------------------------- 3.3/11.9 MB 3.9 MB/s eta 0:00:03
     ----------- ---------------------------- 3.4/11.9 MB 3.4 MB/s eta 0:00:03
     ------------ --------------------------- 3.8/11.9 MB 3.6 MB/s eta 0:00:03
     ------------- -------------------------- 4.0/11.9 MB 3.6 MB/s eta 0:00:03
     ------------- -------------------------- 4.1/11.9 MB 3.5 MB/s eta 0:00:03
     -------------- ------------------------- 4.3/11.9 MB 3.6 MB/s eta 0:00:03
     -------------- ------------------------- 4.4/11.9 MB 3.6 MB/s eta 0:00:03
     -------------- ------------------------- 4.4/11.9 MB 3.6 MB/s eta 0:00:03
     -------------- ------------------------- 4.4/11.9 MB 3.3 MB/s eta 0:00:03
     --------------- ------------------------ 4.7/11.9 MB 3.3 MB/s eta 0:00:03
     ---------------- ----------------------- 4.9/11.9 MB 3.4 MB/s eta 0:00:03
     ----------------- ---------------------- 5.1/11.9 MB 3.4 MB/s eta 0:00:02
     ----------------- ---------------------- 5.2/11.9 MB 3.4 MB/s eta 0:00:02
     ------------------ --------------------- 5.4/11.9 MB 3.4 MB/s eta 0:00:02
     ------------------ --------------------- 5.6/11.9 MB 3.4 MB/s eta 0:00:02
     ------------------- -------------------- 5.8/11.9 MB 3.4 MB/s eta 0:00:02
     -------------------- ------------------- 5.9/11.9 MB 3.4 MB/s eta 0:00:02
     -------------------- ------------------- 6.2/11.9 MB 3.4 MB/s eta 0:00:02
     --------------------- ------------------ 6.3/11.9 MB 3.5 MB/s eta 0:00:02
     --------------------- ------------------ 6.5/11.9 MB 3.5 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 3.5 MB/s eta 0:00:02
     ---------------------- ----------------- 6.8/11.9 MB 3.5 MB/s eta 0:00:02
     ----------------------- ---------------- 7.0/11.9 MB 3.5 MB/s eta 0:00:02
     ------------------------ --------------- 7.2/11.9 MB 3.5 MB/s eta 0:00:02
     ------------------------ --------------- 7.3/11.9 MB 3.5 MB/s eta 0:00:02
     ------------------------- -------------- 7.5/11.9 MB 3.5 MB/s eta 0:00:02
     ------------------------- -------------- 7.6/11.9 MB 3.5 MB/s eta 0:00:02
     -------------------------- ------------- 7.8/11.9 MB 3.5 MB/s eta 0:00:02
     -------------------------- ------------- 8.0/11.9 MB 3.5 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 3.5 MB/s eta 0:00:02
     ---------------------------- ----------- 8.3/11.9 MB 3.5 MB/s eta 0:00:01
     ---------------------------- ----------- 8.5/11.9 MB 3.5 MB/s eta 0:00:01
     ----------------------------- ---------- 8.7/11.9 MB 3.5 MB/s eta 0:00:01
     ------------------------------ --------- 8.9/11.9 MB 3.6 MB/s eta 0:00:01
     ------------------------------ --------- 9.0/11.9 MB 3.6 MB/s eta 0:00:01
     ------------------------------- -------- 9.2/11.9 MB 3.6 MB/s eta 0:00:01
     ------------------------------- -------- 9.3/11.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------- ------- 9.5/11.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 3.6 MB/s eta 0:00:01
     --------------------------------- ------ 9.9/11.9 MB 3.6 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 3.6 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 3.6 MB/s eta 0:00:01
     ---------------------------------- ----- 10.3/11.9 MB 3.7 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 3.7 MB/s eta 0:00:01
     ------------------------------------ --- 10.8/11.9 MB 3.7 MB/s eta 0:00:01
     ------------------------------------ --- 11.0/11.9 MB 3.6 MB/s eta 0:00:01
     ------------------------------------- -- 11.2/11.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 3.6 MB/s eta 0:00:01
     ---------------------------------------  11.7/11.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247958 sha256=de1c68f9a1db7f598ae87e46832a2f02eb3c03c5b4e76a54aa0b6ffd35683965
  Stored in directory: c:\users\prana\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

In [32]:
import pandas as pd
import mysql.connector
import numpy as np

In [35]:
df=pd.read_csv("ap_bus_details.csv")
df=pd.read_csv("Assam_bus_details.csv")
df=pd.read_csv("Chandigarh_bus_details.csv")
df=pd.read_csv("Goa_bus_details.csv")
df=pd.read_csv("HP_bus_details.csv")
df=pd.read_csv("kerala_bus_details.csv")
df=pd.read_csv("Punjab_bus_details.csv")
df=pd.read_csv("Rajasthan_bus_details.csv")
df=pd.read_csv("Telangana_bus_details.csv")
df=pd.read_csv("UttarPradesh_bus_details.csv")
# List of CSV file paths
csv_files=["Ap_bus_details.csv","Assam_bus_details.csv","Chandigarh_bus_details.csv","Goa_bus_details.csv","HP_bus_details.csv","Kerala_bus_details.csv",
            "Punjab_bus_details.csv","Rajasthan_bus_details.csv","Telangana_bus_details.csv","UttarPradesh_bus_details.csv"]
# Read each CSV file into a DataFrame and store it in a list
df=[pd.read_csv(file) for file in csv_files]
# Concatenate all DataFrames in the list
combined_df = pd.concat(df, ignore_index=True)
combined_df.to_csv("bus_routes.csv",index=False)
combined_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),23:45,06h 00m,05:45,4.7,INR 369,27 Seats available
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:25,06h 50m,06:15,4.7,INR 379,29 Seats available
2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,IntrCity SmartBus,A/C Seater / Sleeper (2+1),22:45,07h 00m,05:45,4.5,INR 379,23 Seats available
3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,AdSai RK Travels,Non A/C Seater / Sleeper (2+1),22:10,07h 20m,05:30,3.8,INR 550,23 Seats available
4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,FRESHBUS,Electric A/C Seater (2+2),23:10,06h 05m,05:15,4.6,549,23 Seats available
...,...,...,...,...,...,...,...,...,...,...
2030,Lucknow to Varanasi,https://www.redbus.in/bus-tickets/lucknow-to-v...,PTC-SKYBUS,A/C Seater/Sleeper (2+1),22:30,07h 00m,05:30,4.6,INR 499,16 Seats available
2031,Lucknow to Varanasi,https://www.redbus.in/bus-tickets/lucknow-to-v...,Mahalaxmi Travels,Bharat Benz A/C Seater /Sleeper (2+1),23:15,06h 30m,05:45,3.4,INR 499,13 Seats available
2032,Lucknow to Varanasi,https://www.redbus.in/bus-tickets/lucknow-to-v...,Goyal Travels,A/C Seater / Sleeper (2+1),23:49,06h 31m,06:20,1.8,INR 500,17 Seats available
2033,Agra to Bareilly,https://www.redbus.in/bus-tickets/agra-to-bare...,UPSRTC - BLY0049,Janrath AC Seater 2+3,17:00,05h 30m,22:30,1.6,INR 417,48 Seats available
2034,Agra to Bareilly,https://www.redbus.in/bus-tickets/agra-to-bare...,UPSRTC - BLY0134,Janrath AC Seater 2+2,23:05,05h 55m,05:00,3.9,INR 486,24 Seats available

In [40]:
#add id column
id_column = pd.Series(range(1, len(combined_df) + 1), name='id')
df = pd.concat([id_column, combined_df], axis=1)
df = pd.read_csv("bus_routes.csv")
# replace string to empty string
df['Price'] = df['Price'].str.replace('INR ', '')
#extract the digits(0-9)
df['Seat_Availability'] = df['Seat_Availability'].str.split(' ',n=1).str[0]

In [54]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ---------------------------------------- 0.0/45.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.0 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.0 kB 217.9 kB/s eta 0:00:01
   ---------------------------------------- 45.0/45.0 kB 369.5 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pymysql
import pandas as pd
import numpy as np
myconnection = pymysql.connect(host='localhost', user='root',passwd='@Micromax12',database="redbus")
df = pd.read_csv("bus_routes.csv")
df = df.dropna() #drop null values
a = ",".join(f"{i} {j}"
for i,j in zip(df.columns,df.dtypes)).replace("float64","float").replace("object","text").replace("int64","int") #replace dtypes from pandas to mysql
table_name = "bus_routes"
myconnection.cursor().execute(f"create table {table_name} ({a})")
for i in range(len(df)):
    myconnection.cursor().execute(f"insert into {table_name} values {tuple(df.iloc[i])}")
    myconnection.commit()